// Generated by scripts/generate-brand.py. Geometry is shared with the brand SVGs.
import SwiftUI
struct CineSymbol: Shape {
    func path(in rect: CGRect) -> Path {
        let scale = min(rect.width / 100, rect.height / 104)
        let origin = CGPoint(x: (rect.width - 100 * scale) / 2, y: (rect.height - 104 * scale) / 2)
        var path = Path()
        path.move(to: CGPoint(x: origin.x + 82 * scale, y: origin.y + 20 * scale))
        path.addLine(to: CGPoint(x: origin.x + 36 * scale, y: origin.y + 20 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 18 * scale, y: origin.y + 38 * scale), control1: CGPoint(x: origin.x + 24 * scale, y: origin.y + 20 * scale), control2: CGPoint(x: origin.x + 18 * scale, y: origin.y + 26 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 36 * scale, y: origin.y + 56 * scale), control1: CGPoint(x: origin.x + 18 * scale, y: origin.y + 50 * scale), control2: CGPoint(x: origin.x + 24 * scale, y: origin.y + 56 * scale))
        path.addLine(to: CGPoint(x: origin.x + 64 * scale, y: origin.y + 56 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 72 * scale, y: origin.y + 64 * scale), control1: CGPoint(x: origin.x + 69 * scale, y: origin.y + 56 * scale), control2: CGPoint(x: origin.x + 72 * scale, y: origin.y + 59 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 64 * scale, y: origin.y + 72 * scale), control1: CGPoint(x: origin.x + 72 * scale, y: origin.y + 69 * scale), control2: CGPoint(x: origin.x + 69 * scale, y: origin.y + 72 * scale))
        path.addLine(to: CGPoint(x: origin.x + 30 * scale, y: origin.y + 72 * scale))
        path.addLine(to: CGPoint(x: origin.x + 18 * scale, y: origin.y + 84 * scale))
        path.addLine(to: CGPoint(x: origin.x + 64 * scale, y: origin.y + 84 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 84 * scale, y: origin.y + 64 * scale), control1: CGPoint(x: origin.x + 77 * scale, y: origin.y + 84 * scale), control2: CGPoint(x: origin.x + 84 * scale, y: origin.y + 77 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 64 * scale, y: origin.y + 44 * scale), control1: CGPoint(x: origin.x + 84 * scale, y: origin.y + 51 * scale), control2: CGPoint(x: origin.x + 77 * scale, y: origin.y + 44 * scale))
        path.addLine(to: CGPoint(x: origin.x + 36 * scale, y: origin.y + 44 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 30 * scale, y: origin.y + 38 * scale), control1: CGPoint(x: origin.x + 32 * scale, y: origin.y + 44 * scale), control2: CGPoint(x: origin.x + 30 * scale, y: origin.y + 42 * scale))
        path.addCurve(to: CGPoint(x: origin.x + 36 * scale, y: origin.y + 32 * scale), control1: CGPoint(x: origin.x + 30 * scale, y: origin.y + 34 * scale), control2: CGPoint(x: origin.x + 32 * scale, y: origin.y + 32 * scale))
        path.addLine(to: CGPoint(x: origin.x + 70 * scale, y: origin.y + 32 * scale))
        path.closeSubpath()
        return path
    }
}
